web:
  build: .
  command: bash -c "python app.py"
  ports:
   - "5000:5000"
   - "9181:9181"
#  volumes:
#   - .:/code
  links:
   - redis
   - neo4j
   - worker
   - scheduler
   - rqdashboard

rqdashboard:
  build: .
  command: bash -c "rq-dashboard --redis-host redis --redis-port 6379"
  links:
   - redis

scheduler:
  build: .
  command: bash -c "python core/schedulers.py"
  links:
   - redis
   - neo4j

worker:
  build: .
  command: bash -c "python core/worker.py"
  links:
   - redis
   - neo4j

redis:
  image: redis
  ports:
    - "6379:6379"

neo4j:
  image: neo4j:3.2
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./data:/data